FROM python:3.10-slim-bookworm

RUN apt-get clean \
    && echo "deb http://deb.debian.org/debian testing main" > /etc/apt/sources.list \
    && apt-get update \
    && apt-get install -y pkg-config libseccomp-dev wget xz-utils \
    && apt-get install -y --no-install-recommends zlib1g=1:1.3.dfsg+really1.3.1-1 expat=2.6.2-1 perl=5.38.2-5 libsqlite3-0=3.46.0-1

# copy main binary to /main
COPY main /main
# copy initial env
COPY env /env

# copy config file
COPY conf/config.yaml /conf/config.yaml
# copy python dependencies
COPY dependencies/python-requirements.txt /dependencies/