name: Universal Build

on:
  workflow_call:
    inputs:
      runner:
        required: true
        type: string
      arch:
        required: true
        type: string
      arch_label:
        required: true
        type: string
    secrets:
      DOCKERHUB_USER:
        required: true
      DOCKERHUB_TOKEN:
        required: true

jobs:
  build:
    name: Build ${{ inputs.arch_label }}
    runs-on: ${{ inputs.runner }}

    steps:
      - name: Checkout code
        uses: 