name: Run GoTest

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

concurrency:
  group: test-arm64-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  test:
    name: Test ARM64
    runs-on: arm64_runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install System Dependencies
        run: sudo apt-get install -y pkg-config gcc libseccomp-dev

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20.6

      - name: Install dependencies
        run: go mod tidy

      - name: Compile librar